### ISSUE TITLE
Consider changing logo and colour scheme aqua blue -> Orange to avoid confusion / affiliation with Bitcoin Cash.

### ISSUE THREAD

**Issue by codyellingham** [teambtcmap/btcmap.org#105]
**Is your feature request related to a problem? Please describe.**
The current btcmap.org logo colour scheme feels too close to the "Bitcoin Cash blue", and could lead to confusion about the true Bitcoin-roots of this project. Bitcoin cash is almost dead at this point, but I still felt the need to go and verify that this project was not some kind of secret frontrunner for BCH. I think orange or something else would be much clearer.

![btcmap](https://github.com/teambtcmap/btcmap.org/assets/12945777/0e1bb09b-ba13-46de-89f8-8df7d74c4a13)

**Describe the solution you'd like**
Adjust the logo to use Orange / monochrome, or another colour?

**Describe alternatives you've considered**
None.

**Additional context**
I am happy to do the design work to explore this further if there is interest in pursuing this.

Ideas:
<img width="981" alt="Screen Shot 2023-07-19 at 3 32 50 PM" src="https://github.com/teambtcmap/btcmap.org/assets/12945777/5d3f88aa-0c95-49a3-8173-b256e8844d57">

<img width="825" alt="Screen Shot 2023-07-19 at 3 37 54 PM" src="https://github.com/teambtcmap/btcmap.org/assets/12945777/909fdfc3-c689-4b7c-8539-d7305b6c67f8">

**Comment by dadofsambonzuki** [comment]
Hey @codyellingham - thanks for reaching out and for the mockups.

We've decided to reclaim green! Not everything in the Bitcoin future we all see coming needs to be orange; that would be quite dull!

Non-orange things are OK. 🤟

I understand your point re BCH, but most people coming into Bitcoin don't know what that is and don't have that brand association. BCH is getting less relevant by the day from an already low bar.

Feel free to jump in our Discord if you'd like to contribute the project with your design skills as we're always looking out for contributors.

Cheers,

Nathan
