### ISSUE TITLE
Leaderboard page duplicate entries

### ISSUE THREAD

**Issue by BonHodl** [teambtcmap/btcmap.org#115]
**Describe the bug**
The leaderboard is populated with the same entries multiple times. Seems to grow forever until cookies/site data is deleted from browser.

**To Reproduce**
Go to leaderboard page. Open another tab, navigate to leaderboard to see double entries. Closing previous leaderboard tabs  did not delete the duplicates. I had multiple OSM tabs open as well. This will grow perhaps infinitely? 

**Expected behavior**

**Screenshots**
Included a screenshot where I got up to 4-5 duplicates. 
![Screenshot from 2023-11-29 06-24-18](https://github.com/teambtcmap/btcmap.org/assets/34190903/0b3e916b-fec6-4374-89d6-dba4dad3ee0c)

**Additional context**
Brave Browser was used. Did not test in Firefox/Librewolf.

**Comment by secondl1ght** [comment]
Are you able to reproduce after clearing the site data?

**Comment by secondl1ght** [comment]
Thanks for the report! I believe I pushed a fix, do you mind testing again and letting me know?

**Comment by secondl1ght** [comment]
Thanks again for reporting, I am going to close this issue as I have pushed a fix. Please report any new issues here and we can re-open the ticket if needed. 🙌🏼

**Comment by BonHodl** [comment]
Looks to be fixed. I haven't been able to reproduce.
