### ISSUE TITLE
Remove 'legacy location' graph from stats page.

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap.org#121]
I don't think we need this on the main page now that these have largely been removed.

I think we're handling this through the linting checks now.

**Comment by secondl1ght** [comment]
Ok I removed it from the dash and also the Community leaderboard, but I left it in other places like on the Community page or on the Map... it might still be useful to show in these places for tracking? Hopefully anyone who was using this dash chart for finding these elements knows about the `tagging-errors` lint feed on Discord.
