### ISSUE TITLE
Ability to filter by third party requirement

### ISSUE THREAD

**Issue by yanascz** [teambtcmap/btcmap.org#124]
In light of https://github.com/teambtcmap/btcmap.org/pull/110, it'd be really great to filter out merchants accepting BTC via a 3rd party app (or vice versa). Modification of URL is possible but it's pretty user-unfriendly. By default, no filter shall apply.

It's obvious that this would require up-to-date data set but at least there would be user-friendly filtering available.

**Comment by secondl1ght** [comment]
Thanks @yanascz, I updated the title to reflect what we talked about in #20.
