### ISSUE TITLE
Add map picker to noob form.

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap.org#13]
This enables people to pick the location of the place, greatly reducing the effort for taggers.

**Comment by secondl1ght** [comment]
Complete

**Comment by dadofsambonzuki** [comment]
Probably should curtail the accuracy to 4 decimals or something to avoid display issues.

**Comment by secondl1ght** [comment]
Thanks for the feedback - I trimmed it to 6 decimals because that still displays fine on mobile. It only rounds the visible numbers though so that the underlying data submitted is still more accurate.
