### ISSUE TITLE
International characters break Communities page

### ISSUE THREAD

**Issue by jesterhodl** [teambtcmap/btcmap.org#130]
**Describe the bug**
Communities with international characters, like the French, or Polish 21 communities can get messed up. See repro steps.

**To Reproduce**
1. Go to: https://btcmap.org/communities
2. From the dropdown pick "Dwadzieścia Jeden"
3. The page reloads, everything's fine so far. The address bar shows: https://btcmap.org/communities#Dwadzie%C5%9Bcia%20Jeden
4. So now you think you can go and share the URL. So you go visit it: https://btcmap.org/communities#Dwadzie%C5%9Bcia%20Jeden
5. But it loads with errors:

- The community name is *Dwadzie%C5%9Bcia Jeden*
- The dropdown is not populated with the value
- The local communities do not display

6. It does fix itself only after you pick the right value from the dropdown

**Expected behavior**
When using a link generated by the btcmap like these:
* https://btcmap.org/communities#Dwadzie%C5%9Bcia%20Jeden
* https://btcmap.org/communities#D%C3%A9couvre%20Bitcoin

The international characters should be handled in such a way that the dropdown detects them and page loads correctly.

**Screenshots**
Dropdown is OK after first visit:
![image](https://github.com/teambtcmap/btcmap.org/assets/103882255/700d5a8d-5d68-4150-9aec-c23b56229272)

But when you use visit the generated link it will mess up the name and won't load the communities:
![image](https://github.com/teambtcmap/btcmap.org/assets/103882255/0d4a6a3a-22e7-43ca-8504-2aa6e45a83b9)

**Additional context**
None

**Comment by secondl1ght** [comment]
Thanks for the detailed report on this! We'll get this fixed ASAP.
