### ISSUE TITLE
Android links on website

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap.org#14]
Add a single Android icon on the website that pops a modal for GitHub, F-Droid and Play Store.

Perhaps add in some text about why we encourage F-Droid and Google can get in the bin.

**Comment by secondl1ght** [comment]
Should we get a design for this or wing it?

**Comment by dadofsambonzuki** [comment]
Wing it. It's pretty straightforward I think given the design steer we have already.

I can provide copy if you want.
