### ISSUE TITLE
Consistent payment type display - Web App

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap.org#15]
Without any specific payment tags (i.e. just  `currency:XBT=yes` or `payment:bitcoin=yes`) we should show all three icons (bitcoin/on-chain, lightning and contactless bars) greyed out.

We colour them when we have a specific `payment:blah=yes` tag and we strike them out if we see a 'payment:blah=no' tag.

**Comment by dadofsambonzuki** [comment]
Looks like `payment:blah=no' doesn't remove or strike-out that payment type.

e.g. https://www.btcmap.org/map?lat=11.9675153&long=121.9274626

**Comment by secondl1ght** [comment]
Yes I didn't add that functionality because we don't mention adding those tags in the Wiki: https://github.com/teambtcmap/btcmap.org/wiki/Tagging-Instructions

Do you think people would explicitly add a `no` tag?

**Comment by dadofsambonzuki** [comment]
I'll update the Tagging Instructions.

We've already had feedback that this would be useful.

**Comment by secondl1ght** [comment]
Sounds good - will do

**Comment by dadofsambonzuki** [comment]
Hover overs should be explicit too for accepted, unknown, not accepted.

e.g. 'On-chain accepted', 'On-chain unknown', 'On-chain not accepted'.

**Comment by secondl1ght** [comment]
@dadofsambonzuki are you happy with the way it is now or does this still need improvement?

**Comment by dadofsambonzuki** [comment]
Strikethrough assets still required.

**Comment by dadofsambonzuki** [comment]
Paging @cogentgene - How do we feel about strikethroughs?

**Comment by cogentgene** [comment]
Hey, added them! Check out the Figma file. PS. if I don't respond within a few days, DM me directly in Discord and or Slack or Twitter. 

I just miss these notifications easily :( I guess being bombarded by all sorts just made me immune to checking them lol

![Image](https://user-images.githubusercontent.com/3827304/193257462-2d176098-beaa-427f-aba6-7eed9a2959c1.jpg)

**Comment by dadofsambonzuki** [comment]
They are beautiful Gene.

There was talk about the onchain one being a chain. Where do you stand on
that? I think I prefer the Bitcoin, although I get the logical argument
against.

**Comment by cogentgene** [comment]
@dadofsambonzuki I think I prefer the standard Bitcoin icon ₿. Chain could be mistaken for a link. I think it fairly accepted that Bitcoin symbol ₿ can mean on-chain AND lightning, UNLESS lightning is specifically mentioned with a bolt icon ⚡️ - in which case it becomes clear ₿ means on-chain. I hope..

**Comment by dadofsambonzuki** [comment]
Agreed.

**Comment by secondl1ght** [comment]
Thanks guys - this is complete now
