### ISSUE TITLE
Filter locations by payment type -  Web App

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap.org#20]
On-chain
Lightning
Lightning Contactless

**Comment by secondl1ght** [comment]
This functionality is currently available using URL query params, did we also want to add buttons to the map? I think @bubelov mentioned that we might not want to implement this right now because lots of the tags are not accurate so the filtering will not be accurate either and might confuse people or cause them to miss businesses that do accept a payment method.

**Comment by dadofsambonzuki** [comment]
Fair point re data quality. We see this in the dashboard where individual payment methods don't add to the total.

Let's close for now.

**Comment by secondl1ght** [comment]
> Fair point re data quality. We see this in the dashboard where individual payment methods don't add to the total.
> 
> Let's close for now.

Yeah I also noticed that on the dashboard, but in that location it might be OK to leave it? Was thinking maybe we could have some info tooltips there explaining what tags each one is?

**Comment by yanascz** [comment]
Any ETA when this might be added as a filtering option? Modification of URL is possible but it's pretty user-unfriendly.
Is it worth filing a feature request for that?

**Comment by secondl1ght** [comment]
Hi @yanascz the payment tags are not as widely used as the base bitcoin tags so you would be missing out on merchants if you applied these filters. I think it's safe to assume that almost 100% of merchants accepting bitcoin are probably going to accept lightning if that is the filter you are trying to apply.

**Comment by yanascz** [comment]
I understand your point but in light of https://github.com/teambtcmap/btcmap.org/pull/110, it'd be really great to filter out merchants not accepting BTC via a 3rd party app (or vice versa). Our Czech community put a lot of effort into clearing the data set so it'd work pretty well in Czechia, I hope.

**Comment by secondl1ght** [comment]
I think adding a filter for those third party required locations makes sense, it could be added when the third party icon gets added.

**Comment by yanascz** [comment]
Great! Do you want me to file a follow-up feature request?

**Comment by secondl1ght** [comment]
Sure it couldn't hurt for tracking purposes, thanks!
