### ISSUE TITLE
Create info page with legend etc.

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap.org#21]
Describing the Payment Type colouring.

**Comment by dadofsambonzuki** [comment]
Updated the main issue.

**Comment by secondl1ght** [comment]
Should we get a design for this?

**Comment by dadofsambonzuki** [comment]
Probably. @cogentgene

**Comment by secondl1ght** [comment]
@dadofsambonzuki I was thinking if we dont want to clutter up the map with many components we could create a legend on a /info page of the website and have a single '?' button on the map that links there for users to read more. In addition to having the legend we could have an FAQ potentially and move the WIKI tagging instructions there too so everything is on one page? What do you think?

**Comment by cogentgene** [comment]
Created a basic wiki template. Let me know if you need anything else. I think most items you can just write out?

**Comment by secondl1ght** [comment]
I think we can close this issue - we have the docs design done for when we want to implement it and I will add a map legend to the Wiki.

**Comment by dadofsambonzuki** [comment]
Agree. The icons with higher over are now clear.
