### ISSUE TITLE
Add 'Support Us' Page

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap.org#26]
For donation CTAs.

**Comment by secondl1ght** [comment]
This can be a simple page showing our on-chain address and lightning address, each one can be a link so they are clickable if users have installable apps that recognize them and we could also show QR codes for each as well.

**Comment by cogentgene** [comment]
Added, let me know what you think. See Figma file.

**Comment by dadofsambonzuki** [comment]
We can now integrate the LNbits Tip Jar for LIghtning and On-chain tips.

Tips made can optionally be shown too.

**Comment by secondl1ght** [comment]
This is in progress and will be released soon.
