### ISSUE TITLE
Tidy-up 'Add Location' Page

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap.org#27]
- [x] Updated icons for payment types
- [x] NFC should be Lightning Contactless
- [x] 'Shadowy supertagger' left aligned
- [x] Twitter handle to be split in Merchant handle and Submitter handle
- [x] 'Help Us Improve' centrally aligned or switched to the 'Support Us' page if ready.

**Comment by secondl1ght** [comment]
All complete ✅
