### ISSUE TITLE
Add location modal

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap.org#3]
- [x] Copy
- [x] Design
- [x] Dev

# Copy

## Noobs

Simply fill out the form and we will add the location into OpenStreetMaps for you!

```
Field: Merchant Name
Field: Address
Field: Google Maps URL
Radio: onchain | lightning | ightning contactless/nfc
Field: Notes | Please enter as much detail as possible.
```

You'll be editing like a Super Shadowy Coder in no time.

## Shadowy Super Coders

Once you have an OpenStreetMap account, you can use the [OSM iD web app](https://learnosm.org/en/beginner/id-editor/#the-id-editor) to edit the maps directly on [OpenStreetMap.org](https://www.openstreetmap.org/edit).

Please use the following guidance when editing locations:

### Required tags

`currency:XBT=yes` - This denotes the Bitcoin *currency* is generally accepted.

### Optional tags

`payment:onchain=yes` - This denotes that onchain *payments* are accepted.

`payment:lightning=yes` - This denotes that Lightning *payments* are accepted.

`payment:lightning_contactless=yes` - This denotes that NFC Lightning *payments* are accepted.

`survey:date=yyyy-mm-dd` - This helps mappers know how current the data is. You should verify all data if using this.

### Legacy tags

`payment:bitcoin=yes` - This is a very popular legacy tag implying both `currency:XBT=yes` and `payment:onchain=yes`.

`currency:BTC=yes` - This is a less popular tag, although has some use.

We still search for these tags for general display in the apps, but we won't be specific on the payment types supported. You should consider removing them and updating with the current tagging rules.

### Points, not Ways

Please tag points not ways. If ways already exist, consider adding a point.

**Comment by cogentgene** [comment]
What fields do we need on the form? Or do you want to host the form some other place and just point a link to it? Then I guess our design will be focused on shadowy super coders with a simple button for the noobs.

**Comment by dadofsambonzuki** [comment]
Fields as follows:

Location name
Google Maps URL
Notes

We should encourage in the notes feild to be as descriptive as possible.

@secondl1ght has ideas about where the data is posted.

I'm thinking two tabs on the modal: Noobs | Super Shadowy Coders but happy with whatever you think looks best.

**Comment by secondl1ght** [comment]
@dadofsambonzuki the fields you put in the Figma are different than what you posted above:

> Merchant Name
City, Country
Google Map link
Support for onchain and/or lightning and/or lightning nfc

We can create a Submissions channel on Discord where I can integrate with the Airtable backend I plan on using and it will post notifications there. Once somebody verifies and adds the submission to OSM we can check it off as complete in Airtable. Ill ask Igor today what he thinks about this.

**Comment by dadofsambonzuki** [comment]
Updated the ticket.

**Comment by cogentgene** [comment]
If you have a google maps URL is the address field necessary?

**Comment by cogentgene** [comment]
> onchain | lightning | ightning contactless/nfc

Should these be checkboxes?

**Comment by secondl1ght** [comment]
> > onchain | lightning | ightning contactless/nfc
> 
> Should these be checkboxes?

Yes

**Comment by secondl1ght** [comment]
@dadofsambonzuki let's also make sure we are only collecting the necessary data that we need to add the location to OSM (what are the notes for?). We want it to be as quick and easy as possible for users, I haven't added a location to OSM yet so don't know all the required and optional fields but we should essentially mirror the inputs that OSM needs I think.

**Comment by secondl1ght** [comment]
Also can we not explicitly say Google for the reference URL? Could use DDG, bing, any mapping website really.

**Comment by dadofsambonzuki** [comment]
Agree with your comments @secondl1ght and I'm happy for you to define this. It should be as simple as possible.

There is so much detail we can add in from OSM, but that would complicate things hugely.

The aim is to have the minimal amount of info that will enable the tagging community to verify and add further details.

We should probably (optionally) grab a twitter handle so we can follow-up if needed.
