### ISSUE TITLE
Move Noob form submission to GH Issues.

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap.org#32]
The Discord #location-submission channel is getting messy AF.

The Noob Form on the website should create a new issue in the btcmap-data repo with a location-sumbission tag. Perhaps even giving the submitter the issue ID so they don't hound me via twitter DMs!.

The Discord bot should announce when an issue is opened and closed.

I'd be open to nuking the channel as it makes my head hurt and using the data table back end to create the backlog issues, recognising there will be a handful of dupes.

Issues also help those not on Discord to engage with the project and allow me to share web links when seeking help.

**Comment by secondl1ght** [comment]
Complete
