### ISSUE TITLE
Add category to Noob form and Issue templates in btcmap-data repo.

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap.org#35]

**Comment by secondl1ght** [comment]
Didn't we have that previously and decided to remove it?

**Comment by dadofsambonzuki** [comment]
Don't think so. I think category is a good idea.

Should be free text though.

**Comment by secondl1ght** [comment]
So this would be the popular OSM categories like Restaurant etc.? We could link to the OSM category list for examples?

**Comment by dadofsambonzuki** [comment]
The OSM categories are vast. Don't think we should use them directly as we'd need to keep in sync.

Free text is fine as that is what taggers will use in the category picker field on OSM as it is a search.

**Comment by secondl1ght** [comment]
Complete
