### ISSUE TITLE
Map edit button broken

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap.org#41]
The OSM edit link in the edit icon on the location bubble are not connected to the correct OSM node IDs.

**Comment by secondl1ght** [comment]
@dadofsambonzuki I checked a couple and they are working for me, can you send me a location that is broken please?

**Comment by dadofsambonzuki** [comment]
It seems to be a Node vs Way thing.

If it is a Way it has a different edit URL. We currently send editors to the Node with that ID, not the Way with that ID.

The edit URL needs to be different for Nodes and Ways.

Example:

[https://btcmap.org/map?lat=51.45791535&long=-0.3048932](https://btcmap.org/map?lat=51.45791535&long=-0.3048932)

Opens [https://www.openstreetmap.org/edit?node=432808200]( https://www.openstreetmap.org/edit?node=432808200) and not [https://www.openstreetmap.org/edit?way=432808200#map=19/51.45792/-0.30489](https://www.openstreetmap.org/edit?way=432808200#map=19/51.45792/-0.30489).

**Comment by secondl1ght** [comment]
Ok thanks will fix.

**Comment by secondl1ght** [comment]
Fixed I also added the `relation` type - @dadofsambonzuki
