### ISSUE TITLE
Community pages MVP

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap.org#42]
We should be able to setup communities in the /community space.

This would show a page with node information for that area (bounded rectangle for now) with an embedded map from the API for that area.

API would focus on geographical area e.g. /area/london. Communities focussing on the local vibe, e.g. /community/london-bitcoin-space.

/community/london-bitcoin-space page should embed a map and only load locations from the attached /area/london endpoint.

Could include social info for that community and eventually meet-up info at OSM locations we know.

MVP required.

**Comment by secondl1ght** [comment]
This sounds cool!

**Comment by cogentgene** [comment]
@dadofsambonzuki what was that link you shared with a sample community before? trying to find it... 

Need an idea of what type of info goes there besides map.

**Comment by dadofsambonzuki** [comment]
That wasn't community, it was merchant directory.

Let me work on some mock-ups.

**Comment by cogentgene** [comment]
Oh no worries, can you just give me an idea of what might be included on that page?

**Comment by BenGWeeks** [comment]
Are the design assets going to be added to the repo (e.g., PSD files) or in Figma or similar?

**Comment by dadofsambonzuki** [comment]
Can do.

There are some here already: https://github.com/teambtcmap/btcmap-general
