### ISSUE TITLE
Support us page payment icons.

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap.org#43]
Bring icons inline with map pop-up payment types.

[Screenshot_20221002-070113~2.png](https://user-images.githubusercontent.com/87125117/193441235-e642f4d0-3446-4a84-971b-ab972d9de5b9.png)

**Comment by secondl1ght** [comment]
Good point - I guess it would be good to keep references consistent even outside the map. Will update.

**Comment by secondl1ght** [comment]
Complete
