### ISSUE TITLE
Reduce point clustering

### ISSUE THREAD

**Issue by JhnnWlkr** [teambtcmap/btcmap.org#47]
Reduce the point clustering to make it easier to have an overview of the exact locations of merchants.

**Comment by secondl1ght** [comment]
This has been reduced, can you provide feedback on this current level of clustering please?

**Comment by dadofsambonzuki** [comment]
Much better, although I think we can go a little further.

**Comment by secondl1ght** [comment]
Closing this as we are discussing on the Discord
