### ISSUE TITLE
Spam locations coming in on https://btcmap.org/add-location

### ISSUE THREAD

**Issue by trafficpest** [teambtcmap/btcmap.org#51]
**Is your feature request related to a problem? Please describe.**
I Suggest add captcha or something proving humanity to prevent spam entries on 
https://btcmap.org/add-location

Also Text input for address should have a note something on the line of (locations require a physical address OSM doesnt do service areas. If you are a service industry and do not provide client walk-in make note of it in the description.)

**Comment by secondl1ght** [comment]
Thanks for the issue, I agree this needs to be done. I will get this completed this week.

**Comment by trafficpest** [comment]
added proposed tooltip right after address label in a fork
wasnt sure what you would like to use for a captcha

**Comment by secondl1ght** [comment]
I have added captchas to the forms so this should help with spam prevention. As far as your PR goes I haven't had a chance to look at it yet, but I will!

**Comment by trafficpest** [comment]
it would be nice to do address validation but unfortunately since the global nature it would be impossible. I didnt write much in the tool tip. Also your web development / programming skills are a WAY better than me so look over anything I submit, lol

**Comment by trafficpest** [comment]
your code looks so clean you should see my btc server / frontaccounting intergration you would laugh
