### ISSUE TITLE
Map of additions by tagger

### ISSUE THREAD

**Issue by JhnnWlkr** [teambtcmap/btcmap.org#55]
Add a "show on map" button for each shadowy supertagger, to see where they are most active.

**Comment by secondl1ght** [comment]
We will be implementing tagger profiles soon, would you like it if on the profile page there was a map showing the edits done by that tagger? Instead of a button taking you to the map page?

**Comment by dadofsambonzuki** [comment]
👍

**Comment by JhnnWlkr** [comment]
> We will be implementing tagger profiles soon, would you like it if on the profile page there was a map showing the edits done by that tagger? Instead of a button taking you to the map page?

yeah sounds good

**Comment by secondl1ght** [comment]
Complete
