### ISSUE TITLE
Feature request: add non-edit "details" link to OSM page of the node

### ISSUE THREAD

**Issue by Talkless** [teambtcmap/btcmap.org#57]
It's not necessary to login into OSM page and jump right into editing if you just want to see all the mapping details (OSM tags, history,  etc).

Having "Details" (or similar) link inside location popup referring to https://www.openstreetmap.org/node/10106876793 instead of https://www.openstreetmap.org/login?referer=%2Fedit%3Fnode%3D10106876793 would help.

**Comment by secondl1ght** [comment]
Complete

**Comment by Talkless** [comment]
Thanks @secondl1ght !

**Comment by secondl1ght** [comment]
No problem, sorry it took so long!
