### ISSUE TITLE
Feature request: make current view (coordinates & zoom level) sharable

### ISSUE THREAD

**Issue by Talkless** [teambtcmap/btcmap.org#58]
While there is button that generates sharable link to the Bitcoin-accepting location you clicked on, there's no way to send link to the arbitrary position and zoom level.

For example, OSM official map addes `#map=12/52.2399/21.0361` on every move of the view: https://www.openstreetmap.org/#map=12/52.2399/21.0361 )

**Comment by secondl1ght** [comment]
Update: this is on the TODO list to be completed soon.

**Comment by dadofsambonzuki** [comment]
Implemented in 3452518035dbbb4619810f020acb34ee247df8c8.

**Comment by Talkless** [comment]
Great, thanks @dadofsambonzuki
