### ISSUE TITLE
'More edits' arrow doesn't show more edits on Tagger Profile.

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap.org#69]
**Describe the bug**

The small arrow on the screenshot does not do anything. I presume is should load more edit history.

**To Reproduce**

**Expected behavior**

Area is expanded with more edits loading and an in-line scroll bar.

**Screenshots**

![Screenshot 2023-01-03 at 14 01 17](https://user-images.githubusercontent.com/87125117/210373094-160d5421-aefe-44c9-b110-57480892db8f.png)

**Additional context**

**Comment by secondl1ght** [comment]
That arrow actually isn't a button, it is just attempting to let the user know that the activity section is scrollable because I hid the scrollbar because I thought it didn't look great.

**Comment by dadofsambonzuki** [comment]
Ah, I see. More intuitive on mobile. Will try again on desktop.
