### ISSUE TITLE
Additional social links

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap.org#73]
FB
LinkedIn
nostr
Facebook
Instragram
RSS
Email
WhatsApp

Perhaps we should also consider some sort of integration with LinkTree so we can pull all socials from there for a given account. Not sure how widely it's used though.

**Comment by secondl1ght** [comment]
What's the priority on this?

**Comment by dadofsambonzuki** [comment]
Low.

Can easily be picked up by someone else wanting to contribute.

**Comment by secondl1ght** [comment]
I also wasn't adding IG accounts so if we are going to add FB we could add that one too.

**Comment by dadofsambonzuki** [comment]
Could do, not had any IG yet though.

Should add nostr too, but we'd need a logo designing as there isn't one yet! @cogentgene - let's be first!

We should have a list of supported socials across all platforms as Android and iOS are already behind.

**Comment by secondl1ght** [comment]
I was thinking if we wanted we could go back into the old submissions and grabbed the missed contacts.

**Comment by dadofsambonzuki** [comment]
Yep, this is what I'm doing when adding the polys and population data.

**Comment by dadofsambonzuki** [comment]
Linkedin too. Just had our first ask for that.

**Comment by dadofsambonzuki** [comment]
RSS too.

**Comment by secondl1ght** [comment]
Ok let's keep this issue as a way to track the community socials we need to add. But Linkedin... really?

**Comment by dadofsambonzuki** [comment]
Apparently so.

**Comment by secondl1ght** [comment]
All complete except for RSS since I didn't see any communities with this tag.

**Comment by dadofsambonzuki** [comment]
4x RSS now.

**Comment by dadofsambonzuki** [comment]
Signal too pls.

**Comment by secondl1ght** [comment]
Complete
