### ISSUE TITLE
Community Organization badges for communities.

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap.org#79]
e.g. for Einundzwanzig, decouvre, 2140.

**Comment by secondl1ght** [comment]
Ok I think for this they just need to provide a badge image (probably square or circle format) and then we can use the `organization` tag to display the badges on the profiles.

**Comment by dadofsambonzuki** [comment]
Or maybe we just do something like we did with the sponsorship pills?

**Comment by secondl1ght** [comment]
Ah ok good idea, I didn't think of that. Will do!

**Comment by secondl1ght** [comment]
Maybe we don't need badges since this seems kind of redundant after looking at it if the community name includes the Org: 
![image](https://user-images.githubusercontent.com/85003930/219988513-ddfaff2c-1d97-449a-9cd9-f07902e38725.png)

**Comment by secondl1ght** [comment]
Removed from some areas but left on others.
