### ISSUE TITLE
Mouse clicks does not work on some pins in the map

### ISSUE THREAD

**Issue by Talkless** [teambtcmap/btcmap.org#80]
**Describe the bug**

Some location pins on map does not response to mouse clicks on them, i.e. clicking them does not make info popup appear.

**To Reproduce**

Try clicking on these pins:
![image](https://user-images.githubusercontent.com/292191/220342186-99cb610a-53a6-41c8-b5cd-203430110a62.png)

**Expected behavior**

All pins should respond to mouse clicks to show info popup.

**Screenshots**

Se above.

**Additional context**

Firefox 102.8.0esr on Debian 11 bullseye.

**Comment by dadofsambonzuki** [comment]
Can't reproduce on Firefox 109.0.1 on MacOS 12.3.1

**Comment by secondl1ght** [comment]
Can't reproduce on Brave 1.48.164 on Zorin OS 16.2

**Comment by Talkless** [comment]
It does not reproduce for me also. I believe it might be something to do about unchecking amenities filters and checking them back, but not sure.

**Comment by secondl1ght** [comment]
Ok if you can reproduce please re-open the issue with the additional steps. Thanks

**Comment by Talkless** [comment]
It reproduced again for me in Warsaw: https://btcmap.org/map#18/52.22780/21.00409
![image](https://user-images.githubusercontent.com/292191/234554228-d5c9e9fd-9d40-4261-bb5b-6c184f068efa.png)

**Comment by secondl1ght** [comment]
@Talkless are you able to reproduce consistently or is it still random?

**Comment by Talkless** [comment]
> @Talkless are you able to reproduce consistently or is it still random?

Still happening on the same Warsaw exchange near train station.

**Comment by secondl1ght** [comment]
@Talkless thanks I just pushed a fix, can you confirm it's working now?

**Comment by Talkless** [comment]
@secondl1ght It works fine now, thanks! Tried random other places too and non of them reproduced.

**Comment by secondl1ght** [comment]
Awesome - please report any other bugs you find thanks!
