### ISSUE TITLE
Add breadcumbs

### ISSUE THREAD

**Issue by 3j2009** [teambtcmap/btcmap.org#99]
Add breadcrumbs navigation when 2 or more levels of child pages occur.

This will help with navigation, particularly as the site grows.

See image below:
`Communities` > `Africa` > `African Bitcoiners`
![breadc](https://user-images.githubusercontent.com/126127093/234880874-3c80fab6-5ae5-4758-af50-a96fbb4034e4.png)

**Comment by dadofsambonzuki** [comment]
This is covered within the #113 re-design.
